### PR TITLE
Fix GraphMachine usage Example

### PR DESCRIPTION
**Pull request by ketanbhatt**
The attribute `graph` is not set on the instance of the model, but on the machine.

### CODE REVIEW

**Comment by wtgee** [comment]
HI @ketanbhatt. Since we moved to support multiple models (#128) the graph actually became a property of an individual model rather than the machine. So the example is actually correct, however I can easily understand where the confusion comes from. A `GraphMachine` does have a `get_graph` method which is meant to be used to get that graph so maybe the example would read better as:

```python
from transitions.extensions import GraphMachine as Machine
m = Model()
machine = Machine(model=m, ...)
machine.get_graph().draw('my_state_diagram.png', prog='dot')
```

In the [example notebook](https://github.com/tyarkoni/transitions/blob/master/examples/Graph%20MIxin%20Demo.ipynb) you can also see how we define a convenience method on the model called `show_graph` with the point being that it is actually a property of an individual model.

However if all models should always be in the same state this might actually not be that intuitive. @aleneum @tyarkoni it almost seems to me that it makes sense to move the graph back into the machine rather than the model. The graph, after all, reflects the current status of the machine, not of any individual model. Or is there something I'm missing with how the multiple models should be used?

**Comment by tyarkoni** [comment]
@wtgee, models can now be in different states, so I think it makes sense to keep the graphs in the model. See discussion in #128.

**Comment by aleneum** [comment]
Hi @wtgee,

> However if all models should always be in the same state this might actually not be that intuitive.

that is not necessarily the case. Every model can be in a different state. This [test](https://github.com/tyarkoni/transitions/blob/master/tests/test_core.py#L586) in `test_core` shows how it works (I adapted it to be standalone)

```python
from transitions.extensions import GraphMachine as Machine

class Model:
    pass

def test_multiple_models():
    s1, s2 = Model(), Model() 
    states = ['A', 'B', 'C']

    m = Machine(model=[s1, s2], states=states,
                initial=states[0])
    #self.assertEquals(len(m.models), 2)
    #self.assertEquals(len(m.model), 2)
    m.add_transition('advance', 'A', 'B')
    s1.advance()
    #self.assertEquals(s1.state, 'B')
    print s1.state # >>> B
    #self.assertEquals(s2.state, 'A')
    print s2.state # >>> A

test_multiple_models()
```

**Comment by ketanbhatt** [comment]
@wtgee so I tested it out, and if I do:

```python
from transitions.extensions import GraphMachine as Machine
m = Model()
machine = Machine(model=m, ...)
m.graph.draw('my_state_diagram.png', prog='dot')
```

I get: `AttributeError: 'Model' object has no attribute 'graph'`

It works if I do `machine.graph.draw('my_state_diagram.png', prog='dot')`. Can you check if that is the case with you too?

**Comment by wtgee** [comment]
@tyarkoni @aleneum right, sorry, now my brain is refreshed on that. I haven't yet worked with it in multiple models and August was the month I was much too busy with other things.

@ketanbhatt You are most likely on a slightly outdated version from what the documentation reflects.

**Comment by ketanbhatt** [comment]
Yes that does seem to be the case. I am on `0.4.1`, and I installed using `pip`.

But `transitions/version.py` also says that is the version, and that seems to be the highest number according to tags too. Am I missing something?

**Comment by aleneum** [comment]
Hi @ketanbhatt,

the tag [0.4.1](https://github.com/tyarkoni/transitions/tree/0.4.1) happened about 30 commits ago. We are currently working on release 0.4.2 . If you like to use multiple models as well as the other new features mentioned in the [Changelog](https://github.com/tyarkoni/transitions/blob/master/Changelog.md) you have to install transitions manually at the moment. If you are okay with 0.4.1, have a look at the [documentation](https://github.com/tyarkoni/transitions/blob/0.4.1/README.md) for the tag.

**Comment by ketanbhatt** [comment]
Okay, thank you. I will close this then.
Also, the library is written very beautifully, we are going to use it in our codebase, and it fits in perfectly. 

Thank you again.

**Comment by tyarkoni** [comment]
Sorry, 0.4.2 is long overdue. Will try to push to PyPI today.

**Comment by ketanbhatt** [comment]
Will update in that case 😄

**Comment by tyarkoni** [comment]
Done!
